config/routes.rb
Rails.application.routes.draw do
  get 'contact', to: 'pages#contact'
  get 'about', to: 'pages#about'
  # get '/', to: 'pages#home'
  root to: 'pages#home'

# method   path           controller    action
  get 'restaurants', to: 'restaurants#index'
  post 'restaurants', to: 'restaurants#create'
  get 'restaurants/:id', to: 'restaurants#show', as: :restaurant
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  # Fake DB
  RESTAURANTS = {
    1 => { name: "Dishoom", address: "Shoreditch, London", category: "indian" },
    2 => { name: "Sushi Samba", address: "City, London", category: "japanese" }
  }

  def index
    @category = params[:food_type]
    @restaurants = RESTAURANTS
  end

  def show
    @restaurant = RESTAURANTS[params[:id].to_i]
  end

  def create
    name = params[:name]
    address = params[:address]

    redirect_to restaurants_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheSpoon224</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>NAVBAR</div>
    <%= yield %>
    <div>FOOTER</div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Welcome to the Spoon</h1>
<h2>Were you can find the best restaurants</h2>

<form action="/restaurants" method="get">
  <input type="text" name="food_type" placeholder="What kind of food?">
  <input type="submit">
</form>

<form action="/restaurants" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="text" name="name" placeholder="Name">
  <input type="text" name="address" placeholder="Address">
  <input type="submit">
</form>

<!-- <a href="/restaurants">List Restaurants</a> -->
<%= link_to "List Restaurants", restaurants_path   %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>


<%#= Time.now %>

<% categories = ['japanese', 'portuguese', 'italian', 'chinese', 'american']   %>

<ol>
  <% categories.each do |category| %>
    <li><%= category.capitalize %></li>
  <% end %>
</ol>

<p>You picked: <%= @category %></p>

<table>
  <thead>
    <th>Name</td>
    <th>Address</td>
  </thead>
  <tbody>
    <% @restaurants.each do |id, restaurant| %>
    <tr>
      <td><%= restaurant[:name] %></td>
      <td><%= restaurant[:address] %></td>
      <td>
        <%= link_to "Show", restaurant_path(id) %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/restaurants/show.html.erb
<h1><%= @restaurant[:name] %></h1>
<p>Address: <%= @restaurant[:address] %></p>